### ISSUE TITLE
UI/Docs: Views, Create View (View Library)

### ISSUE THREAD

**Issue by philip-murdoch** [NrsSystems/docs#12]
In the View Library management page, when using the Sort menu, is the option "Most Recent" for "most recent added" or "most recent used"? It's not clear from trying it out. This should be clarified in [views-management.md](https://github.com/NrsSystems/docs/tree/master/digital-displays/views-management.md).

Also note that when sorting the views library by "A-Z", the "Website" view doesn't sort correctly, it remains in the upper left._--update: already fixed_

**Comment by philip-murdoch** [comment]
It's possible the "Website" sorting issue I mentioned has been fixed already in production updates; please verify.

**Comment by philip-murdoch** [comment]
> It's possible the "Website" sorting issue I mentioned has been fixed already in production updates; please verify.

Verified in the Yakima Steel development console, so I presume it's rolled out to production.

**Comment by kyle-nrs** [comment]
Most recent is sort by most recently added, or a sort of New feature. Should we rename the sort option to Newest?

**Comment by philip-murdoch** [comment]
Newest sounds good to me, that should be clear.

**Comment by kyle-nrs** [comment]
Okay. I will have that up on dev today and production EOW next week.

**Comment by philip-murdoch** [comment]
Updated description accordingly.
