### ISSUE TITLE
UI: consistency in VapeDetect name

### ISSUE THREAD

**Issue by philip-murdoch** [NrsSystems/docs#2]
Currently in the UI the duct-mounted sensor is referred to as "Vape Detect", with a space in the name. This appears in:

- the navigation pane on the left side
- the "device type" column in the main dashboard
- the "control Vape Detect relay" action

Also the VapeDetect management page itself has "Vape Detects"--space in the middle, plural "Detects"--as the title. 

My understanding is that the brand name is VapeDetect, without a space. The UI should be updated accordingly.

Also for trademark protection, the brand name should not be used in the plural form or treated as the same as "a sensor device". The management page title should be "VapeDetect sensors" or similar.

**Comment by kyle-nrs** [comment]
VapeDetect is now one word on development. I put the trademark at the header of the VapeDetect landing/list page as well as on the sidenav.

**Comment by kyle-nrs** [comment]
> But all this should be run by a trademark/IP lawyer.

@jgehlsen Feel free to reopen this if we need to change anything else.
