### ISSUE TITLE
Provide feedback link doesn't work

### ISSUE THREAD

**Issue by philip-murdoch** [NrsSystems/docs#20]
The "Provide feedback on this page" link functionality is broken, clicking the link leads to a GitHub 404 error page. This could be related to the project being private, although it still doesn't work even though I'm logged into GitHub.

**Comment by philip-murdoch** [comment]
Per discussion with @kyle-nrs during our meeting on Weds March 17, this issue is due to the repository being under the old NrsSystems company name while the documentation project uses "xsponse" in the URL. Kyle and John are looking into resolving this.

**Comment by kyle-nrs** [comment]
Resolved.
