### ISSUE TITLE
Populate homepage specifics and nav bars for Buttons and Relays

### ISSUE THREAD

**Issue by philip-murdoch** [NrsSystems/docs#36]
I've created new .yml files under _data/navigation and _data/home/specifics to populate the navigation sidebar for the new Button Consoles and Relay Consoles pages and to add the appropriate buttons on the XSPONSE home page. However, none of that is showing up yet. My guess is maybe the relevant HTML files under _includes need to be updated, but I looked at those and don't understand what would need to be changed if so. Help?

**Comment by kyle-nrs** [comment]
So, the .yml files look great.

You have to update `_config.yml`. The top two relate to the tiles/specifics and what order you want them in, feel free to move them around to get the desired order. You can also add a newline after a comma and then move some onto the next line:

```
specific_order: ['xsponse_service', 'digital_displays', 'vape_detect',
                 'button_consoles', 'relay_consoles']
```

The navigation pages are loaded through the `defaults` below, where path is the url path prefix, type of file (this will always be `pages`, but jekyll needs to know.) And then `nav` is the name of the file in the navigation folder for that directory.

**Comment by philip-murdoch** [comment]
Aha! Thanks!
