### ISSUE TITLE
UI/Docs: "Incident Logs" vs. "Action Plan Logs"

### ISSUE THREAD

**Issue by philip-murdoch** [NrsSystems/docs#4]
The Action Plans management page has a button labeled "Incident Logs", which opens a page with the title "Action Plan Logs". We should use one name for consistency.

If changed, this will require updates to [action-plans.md](https://github.com/NrsSystems/docs/tree/master/general-ops/action-plans.md) and [action-plan-logs.md](https://github.com/NrsSystems/docs/tree/master/general-ops/action-plan-logs.md).

**Comment by kyle-nrs** [comment]
The documentation for this can be updated. The website correctly refers to them as incident logs.

**Comment by philip-murdoch** [comment]
- Created a new Incident Logs page (incident-logs.md) with the same documentation but new name.
- Updated the Dashboard and Action Logs pages with the new name and URL to the appropriate page.
- Updated the navigation sidebar to include the Incident Logs page.
- Checked the VapeDetect pages to make sure I didn't miss any references to Action Plan Logs.
